version: '3'

tasks:
  run:
    cmds:
      - task: wasm:build
      - go run ./host
    desc: Run the app
    dir: .
    silent: false

  build:
    desc: Build the app
    cmds:
      - task: wasm:build
      - task: build:{{OS}}

  wasm:build:
    cmds:
      - task: wasm:clean
      - go build -o ./host/main.wasm ./app
    desc: Compile Vecty app into WebAssembly
    dir: .
    env:
      GOOS: js
      GOARCH: wasm
      CGO_ENABLED: 0

  wasm:clean:
    cmds:
      - task: wasm:clean:{{OS}}
    desc: Clean up WebAssembly build
    dir: .
    silent: true

  wasm:clean:windows:
    internal: true
    cmds:
      - del /f ./host/main.wasm
    dir: .
    silent: true

  wasm:clean:darwin:
    internal: true
    cmds:
      - rm -f ./host/main.wasm
    dir: .
    silent: true

  wasm:clean:linux:
    internal: true
    cmds:
      - rm -f ./host/main.wasm
    dir: .
    silent: true

  build:darwin:
    internal: true
    cmds:
      - cmd: echo "Building for darwin amd64"
        silent: true
      - cmd: go build -o ./build/main ./host
        silent: false
    env:
      GOOS: darwin
      GOARCH: amd64

  build:darwin:arm64:
    internal: true
    cmds:
      - cmd: echo "Building for darwin arm64"
        silent: true
      - cmd: go build -o ./build/main ./host
        silent: false
    env:
      GOOS: darwin
      GOARCH: arm64

  build:windows:
    internal: true
    cmds:
      - cmd: echo "Building for windows"
        silent: true
      - cmd: go build -o ./build/main.exe ./host
        silent: false
    env:
      GOOS: windows
      GOARCH: amd64

  build:linux:
    internal: true
    cmds:
      - cmd: echo "Building for linux"
        silent: true
      - cmd: go build -o ./build/main ./host
        silent: false
    env:
      GOOS: linux
      GOARCH: amd64