version: '3'

tasks:
  run:
    cmds:
      - task: wasm:build
      - go run ./cmd
    desc: Run the app
    dir: ./container
    silent: false

  build:
    desc: Build the app
    cmds:
      - task: wasm:build
      - task: build:{{OS}}

  wasm:build:
    cmds:
      - task: wasm:clean
      - go build -o ../container/cmd/main.wasm ./cmd
    desc: Compile Vecty app into WebAssembly
    dir: ./app
    env:
      GOOS: js
      GOARCH: wasm
      CGO_ENABLED: 0

  wasm:clean:
    cmds:
      - task: wasm:clean:{{OS}}
    desc: Clean up WebAssembly build
    silent: true

  wasm:clean:windows:
    internal: true
    cmds:
      - cmd /c "del /F *.wasm"
    dir: ./container/cmd
    silent: true

  wasm:clean:darwin:
    internal: true
    cmds:
      - rm -f *.wasm
    dir: ./container/cmd
    silent: true

  wasm:clean:linux:
    internal: true
    cmds:
      - rm -f *.wasm
    dir: ./container/cmd
    silent: true

  build:darwin:
    internal: true
    cmds:
      - cmd: go build -o ../dist/main ./cmd
        silent: false
    dir: ./container
    env:
      GOOS: darwin
      GOARCH: amd64

  build:darwin:arm64:
    internal: true
    cmds:
      - cmd: go build -o ../dist/main ./cmd
        silent: false
    dir: ./container
    env:
      GOOS: darwin
      GOARCH: arm64

  build:windows:
    internal: true
    cmds:
      - cmd: go build -o ../dist/main.exe ./cmd
        silent: false
    dir: ./container
    env:
      GOOS: windows
      GOARCH: amd64

  build:linux:
    internal: true
    cmds:
      - cmd: go build -o ../dist/main ./cmd
        silent: false
    dir: ./container
    env:
      GOOS: linux
      GOARCH: amd64